targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          build_extensions:
            '^lib/model/{{name}}.dart': 'lib/generated/json/{{name}}.g.dart'
      freezed|freezed:
        options:
          build_extensions:
            '^lib/model/{{name}}.dart': 'lib/generated/freezed/{{name}}.freezed.dart'
      json_serializable:
        options:
          explicit_to_json: true