# TODO: Название
name: flutter_template
description: Шаблон проектов на Flutter
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0
environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Presentation
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  google_fonts: ^6.0.0
  cached_network_image: ^3.2.3

  # Logic
  rxdart: ^0.27.7
  collection: ^1.17.1
  dio: ^5.3.2
  flutter_bloc: ^8.1.3
  provider: ^6.0.5
  equatable: ^2.0.5

  # Data
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  # hive: ^2.0.5
  # hive_flutter: ^1.1.0

  # DI
  get_it: ^7.6.4
  injectable: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # CodeGen
  build_runner: ^2.3.3
  injectable_generator: ^2.4.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  # hive_generator: ^2.0.0

  # DesignGen
  flutter_launcher_icons: ^0.13.0
  flutter_native_splash: ^2.2.9

flutter:
  uses-material-design: true

#  assets:
#    - assets/

flutter_native_splash:
  background_image: assets/splash.png

flutter_icons:
  image_path: "assets/icon.png"
  android: "launcher_icon"
  ios: true
